kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvrwm001
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: nfsserver.ocp4.its4u.local
    path: /var/share/pvrwm_001
  accessModes:
    - ReadWriteMany
