apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1 
  kind: DeploymentConfig
  metadata:
    labels:
      app: api
    name: api
  spec:
    replicas: 1 
    selector:
      app: api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: api
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/acceptance/api:acceptance
          imagePullPolicy: Always
          name: api
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ui
    name: ui
  spec:
    progressDeadlineSeconds: 600
    replicas: 2 
    revisionHistoryLimit: 10
    selector:
      app: ui
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ui
      spec:
        containers:
        - env:
          - name: VOTING_API_SERVICE_HOST
            value: api
          - name: VOTING_API_SERVICE_PORT
            value: "9000"
          image: image-registry.openshift-image-registry.svc:5000/acceptance/ui:acceptance
          imagePullPolicy: Always
          name: ui
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 9090
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: api
    name: api
  spec:
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ui
    name: ui
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ui
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ui
    name: ui
  spec:
    host: ui-acceptance.apps.ocp4.its4u.local
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ui
      weight: 100
    wildcardPolicy: None
  status:
kind: List
